version: '2'
services:
    mongo-cfg-1:
        container_name: "mongo-cfg-1"
        image: mongo
        ports:
            - "30001:27017"
        command: mongod --replSet configReplicaSet --rest --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always
